import { Tasting } from '@/hooks/useTastings';

export const SEED_TASTINGS: Tasting[] = [
  {
    id: 'seed-001-yirgacheffe',
    createdAt: new Date(Date.now() - 86_400_000).toISOString(),
    coffeeName: 'Kochere Natural',
    country: 'Ethiopia',
    region: 'Yirgacheffe',
    farm: 'Kochere Station',
    variety: 'Heirloom',
    processing: 'Natural',
    roaster: 'Onyx Coffee Lab',
    roastDate: '2025-06-01',
    brewMethod: 'V60',
    doseGrams: '20',
    beverageWeightGrams: '300',
    brewTimeSeconds: '200',
    waterTemperatureCelsius: '94',
    dryAroma: 'Jasmine, blueberry, dark chocolate',
    wetAroma: 'Blueberry jam, wine, florals',
    firstImpression: 'Bright and fruity with a juicy mouthfeel',
    acidity: 8,
    sweetness: 9,
    bitterness: 3,
    body: 6,
    balance: 8,
    cleanCup: 9,
    aftertaste: 8,
    overallScore: 92,
    notes: "Extraordinary natural. Blueberry is forward and wine-like. One of the best naturals I've had.",
    topThreeDescriptors: ['Blueberry', 'Jasmine', 'Dark Chocolate'],
    additionalDescriptors: ['Wine', 'Florals'],
    photoUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=480&q=75',
    photos: [],
    favorite: true,
  },
  {
    id: 'seed-002-colombia',
    createdAt: new Date(Date.now() - 5 * 86_400_000).toISOString(),
    coffeeName: 'Las Margaritas',
    country: 'Colombia',
    region: 'Huila',
    farm: 'Finca Las Margaritas',
    variety: 'Caturra, Castillo',
    processing: 'Washed',
    roaster: 'Stumptown Coffee',
    roastDate: '2025-05-20',
    brewMethod: 'Espresso',
    doseGrams: '18',
    beverageWeightGrams: '36',
    brewTimeSeconds: '28',
    waterTemperatureCelsius: '93',
    dryAroma: 'Red apple, caramel, hazelnut',
    wetAroma: 'Caramel, citrus, almond',
    firstImpression: 'Balanced and sweet with bright citrus acidity',
    acidity: 7,
    sweetness: 8,
    bitterness: 4,
    body: 8,
    balance: 8,
    cleanCup: 8,
    aftertaste: 7,
    overallScore: 88,
    notes: 'Excellent espresso. Very balanced and sweet with red fruit notes.',
    topThreeDescriptors: ['Caramel', 'Red Apple', 'Hazelnut'],
    additionalDescriptors: ['Citrus', 'Almond'],
    photoUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=480&q=75',
    photos: [],
    favorite: false,
  },
  {
    id: 'seed-003-panama',
    createdAt: new Date(Date.now() - 12 * 86_400_000).toISOString(),
    coffeeName: 'Gesha Village',
    country: 'Panama',
    region: 'Boquete',
    farm: 'Gesha Village Estate',
    variety: 'Gesha',
    processing: 'Honey',
    roaster: 'Coffee Collective',
    roastDate: '2025-05-10',
    brewMethod: 'Chemex',
    doseGrams: '30',
    beverageWeightGrams: '500',
    brewTimeSeconds: '250',
    waterTemperatureCelsius: '92',
    dryAroma: 'Peach, bergamot, tropical fruit',
    wetAroma: 'Passionfruit, peach blossom, honey',
    firstImpression: 'Incredibly clean, almost tea-like with extraordinary clarity',
    acidity: 9,
    sweetness: 8,
    bitterness: 2,
    body: 5,
    balance: 9,
    cleanCup: 10,
    aftertaste: 9,
    overallScore: 95,
    notes: 'A genuinely rare experience. Honey processed Gesha with extraordinary clarity and complexity.',
    topThreeDescriptors: ['Peach', 'Bergamot', 'Passionfruit'],
    additionalDescriptors: ['Honey', 'Tropical'],
    photoUrl: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=480&q=75',
    photos: [],
    favorite: false,
  },
];

export function seedIfEmpty() {
  const key = 'coffee_journal_tastings';
  const existing = localStorage.getItem(key);
  if (!existing || JSON.parse(existing).length === 0) {
    localStorage.setItem(key, JSON.stringify(SEED_TASTINGS));
  }
}
